spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: dapro_01
      port: 27017
      host: docker-mongo-1

  datasource:
    url: jdbc:mariadb://mysqldb:3306/app_db
    username: db_user
    password: db_user_pass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
